version: "2"
services:
  achat:
    build: .
    environment:
      SPRING_APPLICATION_JSON: '{
        "server.servlet.context-path": "/SpringMVC",
        "server.port": "8089",
        "spring.datasource.url"  : "jdbc:mysql://database:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "logging.level.com.zaxxer.hikari": "INFO",
        "logging.level.org.springframework": "INFO",
        "logging.level.root": "INFO",
        "logging.pattern.console": "%d{yyyy-MM-dd HH:mm:ss} - %-5level - %logger{60} - %msg%n"
      }'
    ports:
      - "8089:8089"
    networks:
      - achat
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "achatdb"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - achat

networks:
  achat:

volumes:
  db:
